config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:show, :index] do
    collection do
      get :owned
    end
  end

  resources :bikes, only: [:index, :show, :new, :edit, :create] do
    resources :bookings, only: [:new, :create, :edit]

    collection do
      get :owned
    end
  end

  root to: "pages#home"
  devise_for :users
  resources :bikes, only: :destroy
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :booking, dependent: :destroy
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[show edit update destroy]

  def index
    @bikes = Bike.all
  end

  def owned
    @bikes = Bike.where(user_id: current_user)
  end

  def show
  end

  def new
    @bike = Bike.new
    @bike.user = current_user
  end

  def edit
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to @bike, notice: "bike was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bike.update(bike_params)
      redirect_to @bike, notice: "bike was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path, notice: "bike was successfully destroyed."
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:price, :description, :photo)
  end

end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @booking = booking.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.save

    redirect_to booking_path(@booking)
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking.update(booking_params)

    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy

    redirect_to booking_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :bike_id, :Checkin, :Checkout, :total_price)
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def owned
    @bookings = Booking.where(user_id: current_user)
  end

  def new
    @booking = Booking.new
    @bike = Bike.find(params[:bike_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    bike = Bike.find(params[:bike_id])
    @booking.bike = bike
    @booking.totalprice = bike.price.to_i * (@booking.checkout - @booking.checkin)

    return unless @booking.save

    redirect_to booking_path(@booking)
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking.update(booking_params)

    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy

    redirect_to owned_bookings_path, notice: "booking was successfully destroyed."
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:checkin, :checkout, :totalprice)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_bike.html.erb
<div>
  <p>
    <strong>Owner:</strong>
    <%= bike.user.email %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= bike.description %>
  </p>

  <p>
    <strong>Price/Day:</strong>
    R$<%= bike.price %>,00
  </p>
</div>

<div class="footer">
  <div class="footer-links2">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/bikes/_form.html.erb
<%= simple_form_for(@bike) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions my-button">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bikes/_my_bikes.html.erb
<div>
  <p>
    <strong>Description:</strong>
    <%= bike.description %>
  </p>

  <p>
    <strong>Price/Day:</strong>
    R$<%= bike.price %>,00
  </p>
</div>

app/views/bikes/index.html.erb
<div class="container d-grid">
  <% @bikes.each do |bike| %>
    <div class="card-product grow">
    <% if bike.photo.attached? %>
        <%= cl_image_tag bike.photo.key, class:"card-image", id:"index-image-card" %>
      <% else %>
        <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" class="card-image" id="index-image-card"/>
    <% end %>
      <div class="card-product-infos">
        <%= render "bike", bike: bike %>
        <%= link_to bike do %>
          <i class="fa-solid fa-eye" style="color: grey"></i>
        <% end %>
      </div>
    </div>

  <% end %>
</div>
<div class="container">

  <%= link_to  new_bike_path  do %>
      <i class="fa-solid fa-square-plus" id="button_add" style="color: grey"></i>
  <% end %>
</div>

app/views/bikes/new.html.erb
<div class="container">
<%= render "form", bike: @bike %>
</div>

<div class="footer">
  <div class="footer-links2">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/bikes/owned.html.erb
<div class="container">
  <% @bikes.each do |bike| %>
  <div class="card-trip">
    <% if bike.photo.attached? %>
        <%= cl_image_tag bike.photo.key, class:"card-image", id:"index-image-card" %>
      <% else %>
        <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" class="card-image" id="index-image-card"/>
    <% end %>
    <div class="card-trip-infos">
      <div>
        <%= render "my_bikes", bike: bike %>
        <%= link_to bike do %>
          <i class="fa-solid fa-eye" style="color: grey"></i>
        <% end %>
      </div>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        <%= link_to bike_path(bike), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash" style="color: grey"></i>
        <% end %>
    </div>
  </div>
        <% end %>
</div>

app/views/bikes/show.html.erb
<div class="container">
  <div class="card-trip">
    <% if @bike.photo.attached? %>
        <%= cl_image_tag @bike.photo.key, class:"card-image", id:"index-image-card" %>
      <% else %>
        <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" class="card-image" id="index-image-card"/>
  <% end %>
    <div class="card-trip-infos">
      <div>
        <%= render "bike", bike: @bike %>
          <%= link_to new_bike_booking_path(@bike) do %>
          <i class="fa-solid fa-calendar-plus" style="color: grey"></i>
          <% end %>
      </div>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      <% if @bike.user == current_user %>
        <%= link_to bike_path(@bike), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash" style="color: grey"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/booking/_booking.html.erb
<div>

  <p>
    <strong>check-in:</strong>
    <%= booking.checkin %>

    <strong>check-out:</strong>
    <%= booking.checkout %>
  </p>
  <p>
    <strong>bike-booked:</strong>
    Owner:<%= booking.user[:email] %>
    Description:<%= booking.bike[:description] %>
  </p>
  <p>
    <strong>Total price:</strong>
    <%= booking.totalprice %>
  </p>
</div>

app/views/booking/edit.html.erb
<h1>Edit Booking</h1>

<%= render "bookings/shared/form", booking: @booking %>

<%= link_to "See Booking", booking_path(@booking) %>

app/views/booking/index.html.erb
<div class="cards">
  <div class="bookings" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://d33v4339jhl8k0.cloudfront.net/docs/assets/55f25845c69791729524c132/images/5e5f96c12c7d3a7e9ae8a5c1/file-9N4eqOQFjb.png)">
    Bookings
</div>

app/views/booking/show.html.erb
<div class="container">
  <div class="card-trip">
    <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" />
    <div class="card-trip-infos">
      <div>
        <%= render "booking", booking: @booking  %>
          <%# <%= link_to "add booking", new_bike_booking_path(@bike) %>
      </div>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
    </div>
  </div>
  <%= link_to "Bike park", bikes_path %>
  <%= link_to booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
    <i class="fa-solid fa-trash"></i>
  <% end %>
</div>

app/views/bookings/_booking.html.erb
<div>

  <p>
    <strong>check-in:</strong>
    <%= booking.checkin %>

    <strong>check-out:</strong>
    <%= booking.checkout %>
  </p>
  <p>
    <strong>bike-booked:</strong>
    Owner:<%= booking.bike.user[:email] %>
    Description:<%= booking.bike[:description] %>
  </p>
  <p>
    <strong>Total price:</strong>
    R$<%= booking.totalprice %>,00
  </p>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [@bike, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :checkin %>
    <%= f.input :checkout %>
  </div>

  <div class="form-actions my-button">
    <%= f.button :submit%>
  </div>
<% end %>

app/views/bookings/index.html.erb

<div class="container">
        <% @bookings.each do |booking| %>
  <div class="card-trip">
    <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" />
    <div class="card-trip-infos">
      <div>
          <%= render "booking", booking: booking  %>
          <%= link_to booking do %>
            <i class="fa-solid fa-eye" style="color: grey"></i>
          <% end %>
      </div>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
          <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-trash" style="color: grey"></i>
          <% end %>
    </div>
  </div>
  <% end %>
</div>

<script>
    window.onscroll = function() {myFunction()};

    var navbar-lewagon = document.querySelector('.navbar-lewagon');
    var sticky = navbar-lewagon.offsetTop;

    function myFunction() {
      if (window.pageYOffset >= sticky) {
        navbar.classList.add("sticky");
      } else {
        navbar.classList.remove("sticky");
      }
    }
</script>

app/views/bookings/new.html.erb
<div class="container">
<%= render "form", booking: @booking %>

</div>

app/views/bookings/owned.html.erb
<div class="container">
  <% @bookings.each do |booking| %>
    <div class="card-trip">
      <% if booking.bike.photo.attached? %>
          <%= cl_image_tag booking.bike.photo.key, class:"card-image", id:"index-image-card" %>
        <% else %>
          <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" class="card-image" id="index-image-card"/>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <%= render "booking", booking: booking  %>
        </div>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash" style="color: grey"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="card-trip">
  <% if @booking.bike.photo.attached? %>
        <%= cl_image_tag @booking.bike.photo.key, class:"card-image", id:"index-image-card" %>
      <% else %>
        <img src="https://semexe.com/blog/wp-content/uploads/2022/03/Scalpel-personalizada-por-Black-tiger-74.jpg" class="card-image" id="index-image-card"/>
  <% end %>
    <div class="card-trip-infos">
      <div>
        <%= render "booking", booking: @booking  %>
      </div>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      <%= link_to booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
        <i class="fa-solid fa-trash" style="color: grey"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentLebikes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "shared/navbar" %>

    <%= yield %>



    </div>

  </body>
</html>

app/views/pages/home.html.erb
 <div class="banner">
    <div id="container">
      <div class="title">
       <span> Rent LeBikes! </span>
        <p>Travel far and cheap with your <strong>LeBike</strong> by your side!</p>
        <a href="bikes" class="my-button">Browse Bikes</a>
        <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= "home-navbar" if action_name == 'home' %>">
  <div class="container-fluid">

    <%= link_to bikes_path, class: "navbar-brand" do %>
      <%= image_tag "https://icon-library.com/images/bike-icon/bike-icon-14.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", owned_bookings_path, class: "dropdown-item" %>
              <%= link_to "My bikes", owned_bikes_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>